### PR TITLE
first galactic push

### PR DESCRIPTION
**Pull request by girvenavery2022**
This pull request is to port of foxy to galactic. it also includes some changes that include finer tuning of slam toolbox, single-I waypoints, and a serialized map of the single-I field in galactic

### CODE REVIEW

**Review by dcutting133 — APPROVED** [review]

**Comment by dcutting133** [comment]
I think you told me this, but was DWA better than pure pursuit in your tests?

**Comment by dcutting133** [comment]
I'm thinking we should open a different issue for discussion on custom planners since I'm assuming Ohm will want to be involved

**Comment by girvenavery2022** [comment]
on the foxy branch, I had better luck with pure pursuit on both sim and on the physical robot. On galactic, I am actually very very surprised at how well DWB is performing with very little changes. I haven't tested RPP on galactic tho

**Comment by girvenavery2022** [comment]
yeah we should open up a new discussion on our own custom planners, because I don't see why they wouldn't want to be involved

**Pull request merged**
